name: Synchronize Controller docs to asciidoc

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          repository: ansible/aap-docs
          ref: main

      - name: install pandoc
        run: sudo apt-get -y update && sudo apt-get -y install pandoc

      - name: config docs-bot
        run: |
          git config --global user.email "docs-bot@redhat.com"
          git config --global user.name "docs-bot"

      - name: clone product-docs
        uses: actions/checkout@v3
        with:
          repository: ansible/product-docs
          ref: main
          path: product-docs
          ssh-key: ${{ secrets.DOCS_BOT_KEY }}

      - name: rsync rst files
        run: |
          rsync -vr --delete --relative \
            --exclude='**/*.html' \
            --exclude='**/*.css' \
            --exclude='**/*.js' \
            --exclude='**/*.json' \
            --exclude='**/*.yaml' \
            --exclude='**/*.yml' \
            --exclude='**/*.xml' \
            --exclude='**/*.png' \
            --exclude='**/*.svg' \
            --exclude='**/*.ttf' \
            --exclude='**/*.woff' \
            --exclude='**/*.py' \
            --exclude='**/*.eot' \
            --exclude='**/*.po' \
            --exclude='**/*.ico' \
            --exclude='**/*.map' \
            --exclude='**/*.txt' \
            --exclude='**/*.conf' \
            --exclude='**/Makefile' \
            --exclude='_*/*' \
            --exclude='**/_*/*' \
            --exclude='**/locale/*' \
            --exclude='userguide/*' \
            --exclude='release-notes/*' \
            --exclude='contrib/*' \
            ./product-docs/**/ \
            sync
          rm -rf product-docs

      - name: convert rst to adoc
        run: |
          cd sync
          find . -name "*.rst*" | while read i; do pandoc -f rst -t asciidoc "$i" -o "${i%.*}.adoc"; done
          find . -name "*.rst" -type f -delete
          mv product-docs controller-docs

      - name: commit files
        run: |
          git add . --all
          git commit -m "Synchronize Controller docs to asciidoc"

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          directory: sync
          github_token: ${{ secrets.DOCS_BOT_PAT }}
          branch: main
